### ISSUE TITLE
truststore file passing as a config

### ISSUE THREAD

**Issue by jay999123** [macronova/kafka-connect-jms#3]
Hi,
I've a `truststore.jks` file and I want to pass it as part of the config. But I don't not see any configuration defined.Is there any other way I can so that?

**Comment by macronova** [comment]
Is the trust store used to connect to JNDI server or directly JMS? What JMS server you are using? I think we may miss `jms.extra.params` feature (analogical to `jndi.extra.params` that is already supported).

**Comment by jay999123** [comment]
I'm using the `truststore.jks` to trust the server that I'm trying to connect to consume the messages from JMS topic. The server is wildfly

**Comment by jay999123** [comment]
and also I've to pass the truststore password

**Comment by macronova** [comment]
I have been looking at configuration options of WildFly client and it seems that it does not expose special configuration for trust store. You should be fine importing the certificate to default trust store used by JVM in Kafka Connect.

**Comment by jay999123** [comment]
Along with trust/key store importing, I also need to add jboss specific parameters. Anyway I'm closing the issue as I've added below parameters in the code and made it available as config.

"jms.secured": "true",
"jms.keystore.path": "/truststore/truststore.jks",
"jms.keypass": "abcdefgh"

Thanks,
